#!/bin/bash
#Pseudo FileSystem - presents dynamic or virtual data generated by the operating system

#cpu info
cat /proc/cpuinfo

#live memory usage — not stored anywhere, just generated by the kernel
cat /proc/meminfo

#all information about devices that are mounted to pseudo filesystem
#mounting - how the OS connects storage devices, network shares, or pseudo filesystems to your working environment
cat /proc/mounts

#what network devices are connected
cd /proc/net
ls           #netstat command inside
netstat      #list all devices and statistics 

cat /proc/net/netstat

#du - disk usage
du /home/users/julia/Documents/

#to print a summary of disk usage
du -s /home/users/julia/Documents/

#to print in human-readable way
du -h /home/users/julia/Documents/